document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<title>exmple</title>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--front color required-->");
document.writeln("");
document.writeln("	<div id = \'tag1\' style = \'color:red;\'>PINK</div>");
document.writeln("	<div id = \'tag2\' style = \'color:red;\'>PINK(required):</div>");
document.writeln("	<div id = \'tag3\' style = \'color:red;\'>PINK</div>");
document.writeln("	<label for=\'lastname1\' class=\'test1\'>Last name (required): </label>");
document.writeln("	<input id=\'lastname1\' type=\'text\' size=\'25\' value=\'\'/><br>");
document.writeln("	<label for=\'lastname2\' class=\'test\'>Last name : </label>");
document.writeln("	<input id=\'lastname2\' type=\'text\' size=\'25\' value=\'\'/><br>");
document.writeln("	<label for=\'lastname3\' class=\'test3\'>Lfdf (required): </label>");
document.writeln("	<input id=\'lastname3\' type=\'text\' size=\'25\' value=\'\'/><br>");
document.writeln("	<label for=\'lastname4\' class=\'test4\'>Lfdf (required): </label>");
document.writeln("	<input id=\'lastname4\' type=\'text\' size=\'25\' value=\'\'/><br>");
document.writeln("	<label for=\'lastname5\' class=\'test\'>Lfdf (required): </label>");
document.writeln("	<input id=\'lastname5\' type=\'text\' size=\'25\' value=\'\'/><br>");
document.writeln("	<style type=\'text/css\'>");
document.writeln("  	.test {");
document.writeln("    	color:red;");
document.writeln("  	}");
document.writeln("	</style>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!--aria-label-->");
document.writeln("	username1<input type=\'text\' name=\'username1\'><br>");
document.writeln("	username2<input type=\'text\' name=\'username2\' aria-label=\'username2\'><br>");
document.writeln("	username3<input type=\'text\' name=\'username3\'><br>");
document.writeln("");
document.writeln("");
document.writeln("<!--img.alt-->");
document.writeln("	<img src= \'images/jpg1.jpg \' alt= \'Sample1\' id= \'hj1\'/> picture1 ");
document.writeln("	<img src= \'images/jpg2.jpg \' alt= \'Sample2\' id= \'hj2\'/> picture2 ");
document.writeln("	<img src= \'images/jpg3.jpg \' alt= \'\' id= \'hj3\'/> picture3 ");
document.writeln("	<img src= \'images/jpg4.jpg \' alt= \'Sample1\' id= \'hj4\'/> picture4 ");
document.writeln("	<img src= \'images/jpg5.jpg \' alt= \'Sample2\' id= \'hj5\'/> picture5 ");
document.writeln("	<img src= \'images/jpg6.jpg \' alt= \'Sample1\' id= \'hj6\'/> picture6");
document.writeln("	<img src= \'images/jpg7.jpg \' alt= \'\' id= \'hj7\'/> picture7");
document.writeln("	");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
